# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 119bb85f1d721b254072c844030cd28ba938154acee524d233fadb0852072ca45d9c3450942072490ba4d4c6239c805657c6eed7604fbff0e29b2e0eba28561a

test:
  secret_key_base: 479073b82d41f90e035e98bc0be3ccfc28d75ba326cb38b0b5148a5439e8c846ba30a88eb4011afbc747914144e422340dbf7e604388a40b4d74efe9d98f0679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
